---
format:
  pdf:
    documentclass: scrarticle
    # tables: true
    extra-dependencies:
      - float
    # include-in-header:
    #   - text: |
    #       \usepackage{multirow}
title: Lista 01 - Planejamento e Análise de Experimentos (MAE0316)
date: last-modified
date-format: long
lang: pt
geometry:
    - left=3cm
    - top=3cm
    - bottom=2cm
    - right=2cm
author: 
    - name: Caio M. de Almeida - 15444560
    - name: Eduardo Yukio G. Ishihara - 15449012
    - name: Gustavo S. Garone - 15458155
    - name: Ian B. Loures - 15459667
    - name: João Victor G. de Sousa - 15463912
execute:
  echo: false
fig-align: center
fig-cap-location: top
bibliography: references.bib
csl: associacao-brasileira-de-normas-tecnicas.csl
engine: julia
---

```{julia}
#| output: false
# using Pkg; Pkg.add(["GLM", "Plots", "Distributions", "DataFrames", "PrettyTables", "LaTeXStrings", "CSV"])
```

`\vspace{-0.5cm}\noindent\rule{\textwidth}{1pt}`{=latex}

Nesta lista, usaremos "$.$" como separador decimal.

# Exercício 1

## Item a

Analisamos um estudo de coorte sobre os efeitos da "COVID longa" ou Síndrome
pós-COVID-19 no trabalho de @rocha_sindrome_2024. O estudo utilizou o método de
coorte ambidirecional com indivíduos de três hospitais de Cuiabá. Observações
foram colhidas do prontuário desses pacientes e posteriormente $6$ e $12$ meses
após alta hospitalar por telefone. Foram perguntados fatores socioeconômicos dos
indivíduos, além de sintomas comuns da "COVID longa", como fadiga e problemas de
memória.

Na análise de dados, foram consideradas pelos pesquisadores comorbidades como
hipertensão, diabetes, obesidade e doenças cardíacas. Para os sintomas,
classificaram como musculares, neuropsiquiátricos, dermatológicos,
cardiovasculares e pulmonares.

Acreditamos que o estudo tenha uma base metodológica, no geral, sólida, mas que a
dependência na descrição por telefone dos entrevistados pode ter comprometido a
integridade das conclusões. Isso foi parcialmente reconhecido pelos autores, que
perceberam que a obesidade era subrepresentada quando comparada com o IMC
calculado a partir da altura e peso dos entrevistados. Isto é, dos
entrevistados, quando perguntavam se estavam com sobrepeso, responderam
positivamente apenas $11$ dos $46$ identificados com obesidade pelo IMC. Os
autores consideraram isso na análise dos dados, mas não há discussão sobre
outras imprecisões.

## Item b

Pode ser que haja diferença entre as conclusões dos estudos. No primeiro estudo,
fatores como viés de seleção (por exemplo, selecionar pacientes que optaram pelo
estudo, pois utilizam a medicina convencional, e paciente que optaram por não
usar o remédio, pois utilizam exclusivamente a medicina alternativa) e menor
aleatorização. No segundo estudo, ao selecionar previamente o grupo, e então
efetuar um ensaio randomizado, espera-se que o processo de amostragem aleatória
faça com que os dois grupos, na média, tenham indivíduos semelhantes. Logo, a
amostragem aleatória forneceria resultados mais robustos e conclusões mais
acuradas ao atenuar fatores intrínsecos das unidades amostrais dentre os grupos,
como a gravidade da doença, estilos de vida ou fatores biológicos.

## Item c

Um resultado possível, que não considera vieses dos investigadores ou
resultados, é que, no primeiro estudo, o remédio já estava sendo aplicado em
pacientes nos estágios avançados da doença como medida emergencial, enquanto no
segundo estudo o remédio foi aplicado tanto em pacientes com doença avançada
quanto leve ou moderada. Logo, uma taxa de cura menor no primeiro estudo poderia
ser explicada pela ineficiência do medicamento de conter a doença no estágio
avançado, enquanto funciona bem no geral, como aponta o segundo estudo.


# Exercício 2

É apresentado um estudo prospectivo, aleatorizado, experimental (analítico) e
controlado por grupo controle, sobre a aplicação de determinado tratamento -
oxigenação específica - em ratos com diabete (população objetivo). Como
hipótese, buscaram descobrir se existe efeito do oxigênio hiperbárico na
cicatrização de feridas cirúrgicas nesta população. Como fator extrínseco
explicativo e premeditado consta a exposição ou não - caracterizando dois níveis para esse
fator - das unidades experimentais (ratos com diabete induzida) ao tratamento
com oxigênio hiperbárico, uma exposição com intervenção. Uma possível fonte de
variação intrínseca (externa) é a própria variação biológica dos ratos, que pode
acelerar ou retardar a cicatrização. A repetição foi realizada com diversos
ratos por grupo (que receberam ou não o tratamento), cujo número pode ser 
aumentado a fim de gerar mais repetições. Variações externas como
níveis glicêmicos inadequados no sangue foram tratadas ao desconsiderar $6$
desses ratos. Variações acidentais tentaram ser minimzadas por preocauções dos
pesquisadores. Por se tratar de um estudo experimental, não podemos descrever
unidades observacionais, nem se encaixa como longitudinal ou transversal.
A unidade observacional são as amostras de tecido coletadas. Fontes de
mascaramento, como o viés dos pesquisadores, foram relatadas como minimizadas.

# Exercício 3

## Item a

O contraste $p=1$ pode ser usado para testar se o efeito da dose zero difere do
efeito da dose um, enquanto o contraste $p=2$ pode ser usado para comparar o
efieto da dose dois conjuntamente com as doses um e dois. Ambos os constrastes
seriam nesse exemplo usados para encontrar a dose limiar de efeito.

## Item b

Assumindo tamanho amostral igual para as doses, os constrastes são ortogonais:

$$
\begin{aligned}
(-1) \cdot (-1) + 1 \cdot (-1) + 0 \cdot 2 &= 0 \\
(-1) \cdot (-1) + 1 \cdot (-1) + 0 \cdot (-1) + 0 \cdot 3 &= 0 \\
(-1) \cdot (-1) + (-1) \cdot (-1) + 2 \cdot (-1) + 0 \cdot 3 &= 0
\end{aligned}
$$

## Item c

A hipótese $\mathcal{H}_2$ é a mais apropriada para testar a dose limiar uma vez
que busca a primeira dose $j$ a possuir uma média significativamente maior que
as anteriores, que são iguais, assumindo doses crescentes. Caso não exista,
caímos na hipótese de não efeito $\mathcal{H}_0$. Não sugeririamos outra hiótese
para este problema.

## Item d

Construímos a tabela a partir dos dados do enunciado. Usamos os desvios padrões ao quadrado para determinar o MQE dentro de cada dose.

\begin{table}[]
\centering
\caption{Doses}
\begin{tabular}{c|ccccc}
             & \multicolumn{4}{l}{Coeficiente (q)} \\
Dose  (mg/kg/dia)  &  SSQ   &   GL   & MQE   \\
             \cline{1-6}
             & Controle   &  9.4864 & 11    & 0     & 0.8624   \\
             & 10             & 5.3824 & 11    & 0     & 0.4893   \\
             & 20            & 7.6729 & 11    & 3     & 0.6975   \\
            & 30             & 5.3824 & 11    & -1    & 0.4893  \
	    & 30             & 3.4969 & 11    & -1    & 0.3179  
\end{tabular}
\end{table}

Note, portanto, que $SSE = 104.3504 + 59.2064 + 84.4019 + 59.2064 + 38.4659 = 345.631$ e $GL_{Total} = 5 \times 11 = 55$. Portanto, $MQE = \frac{SSE}{GL_{Toal}} = 6.2842$, que também é o estimador não viesado para $\sigma^2$.

Construímos a tabela de contrastes de Helmert:

\begin{table}[]
\centering
\caption{Contrastes usados}
\begin{tabular}{c|ccccc}
             & \multicolumn{5}{l}{Coeficiente (q)} \\
Contraste(p) & 0     & 1     & 2     & 3     & 4   \\
             \cline{1-6}
             & -1    & 1     & 0     & 0     & 0   \\
             & -1    & -1    & 2     & 0     & 0   \\
             & -1    & -1    & -1    & 3     & 0   \\
             & -1    & -1    & -1    & -1    & 4  
\end{tabular}
\end{table}

Para uma hipótese $\mathcal{H}: L_p$ temos o estimador:

$$
\hat{L_j} = \sum^a_{i}c_{j,i} \bar{Y}_i
$$
em que $c_i$ são os elementos do contraste e
$$
\mathrm{Var}(\hat{L_j}) = \mathrm{MSE} \sum^a_{i=1} \frac{c_{j,i}^2}{n_i}
$$

Disso, construímos a estatística do teste
$$
T_p = \frac{\hat{L_j} - 0}{\sqrt{\hat{\mathrm{Var}}(\hat{L_j})}}
\stackrel{\mathcal{H}_0}{\sim} t_{12}
$$

Estamos testando, em todas as hipóteses, $L = 0$. Logo, para cada contraste, temos as seguintes
estatísticas $\hat{L_j}$:
$$
\begin{cases}
\hat{L_1} = -0.060\\
\hat{L_2} = 0.740\\
\hat{L_3} = 4.130\\
\hat{L_4} = 10.930\\
\end{cases}
$$
Com as seguintes variâncias:
$$
\begin{cases}
\hat{\mathrm{Var}}(\hat{L_1}) = 1.0474\\
\hat{\mathrm{Var}}(\hat{L_2}) = 3.142\\
\hat{\mathrm{Var}}(\hat{L_3}) = 6.284\\
\hat{\mathrm{Var}}(\hat{L_4}) = 10.474\\
\end{cases}
$$
Então, são as estatísticas dos testes $T_p$:
$$
\begin{cases}
T_1 = -0.059 \\
T_2 = 0.417\\
T_3 = 1.647\\
T_4 = 3.377\\
\end{cases}
$$
Temos que, para o grau de significância de $5\%$, o quantil de corte é $1.782$. Portanto, a $5\%$ de significância, há evidências para rejeitar a hipótese nula apenas para o contraste $4$.


# Exercício 4

# Referências

:::{.refs}
:::


